apiVersion: v1
kind: Pod
metadata:
  name: dind-sock-pod
  labels:
    app: dind-sock
spec:
  containers:
  - name: dind-sock-container
    image: docker:dind
    command: ["sleep", "1000"]
    volumeMounts:
    - name: dind-sock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dind-sock
    hostPath:
      path: /var/run/docker.sock
