apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap-env
spec:
  containers:
  - name: container
    image: k8s.gcr.io/busybox
    command: ["/bin/bash", "-c", "echo SPECIAL_LEVEL=$(SPECIAL_LEVEL) and SPECIAL_TYPE=$(SPECIAL_TYPE)"]
    env:
    - name: SPECIAL_LEVEL
      valueFrom:
        configMapKeyRef:
          name: special-config-v1
          key: SPECIAL_LEVEL
    - name: SPECIAL_TYPE_KEY
      valueFrom:
        configMapKeyRef:
          name: special-config-v1
          key: SPECIAL_TYPE
  restartPolicy: Never


