
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config-v1
data:
  SPECIAL_LEVEL: very
  SPECIAL_TYPE: charm
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap-env
spec:
  containers:
  - name: container
    image: k8s.gcr.io/busybox
    command: ["/bin/sh", "-c", "echo SPECIAL_LEVEL=$(SPECIAL_LEVEL) and SPECIAL_TYPE=$(SPECIAL_TYPE)"]
    env:
    - name: SPECIAL_LEVEL
      valueFrom:
        configMapKeyRef:
          name: special-config-v1
          key: SPECIAL_LEVEL
    - name: SPECIAL_TYPE_KEY
      valueFrom:
        configMapKeyRef:
          name: special-config-v1
          key: SPECIAL_TYPE
  restartPolicy: Never
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config-v2
data:
  cert: certificate-value
  password: password-value
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap-envfrom
spec:
  containers:
    - name: container
      image: busybox
      command: ["/bin/sh", "-c", "env"]
      envFrom:
      - configMapRef:
          name: special-config-v2
  restartPolicy: Never
---
apiVersion: v1
kind: Secret
metadata:
  name: special-secret-v3
stringData:
  PASSWORD: very-strong-password
  USERNAME: very-big-admin
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets-volume
spec:
  containers:
    - name: container
      image: busybox
      command: ["/bin/sh", "-c", "ls -l /etc/secrets/"]
      volumeMounts:
      - name: secrets-volume
        mountPath: /etc/secrets
  volumes:
  - name: secrets-volume
    secret:
      secretName: special-secret-v3
  restartPolicy: Never
---
