apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap-envfrom
spec:
  containers:
    - name: container
      image: busybox
      command: ["/bin/sh", "-c", "env"]
      envFrom:
      - configMapRef:
          name: special-config-v2
  restartPolicy: Never



