
apiVersion: v1
kind: Pod
metadata:
  name: pod-volumes-emptydir
spec:
  initContainers:
  - name: container-init
    image: busybox
    command: ["touch", "/shared-dir/file-1", "shared-dir-memory/file-2"]
    volumeMounts:
    - name: pod-shared-volume
      mountPath: /shared-dir
    - name: pod-shared-volume-memory
      mountPath: /shared-dir-memory
  containers:
  - name: container-1
    image: busybox
    command: ["sleep", "1000"]
    volumeMounts:
    - name: pod-shared-volume
      mountPath: /shared-dir
    - name: pod-shared-volume-memory
      mountPath: /shared-dir-memory
  - name: container-2
    image: busybox
    command: ["sleep", "1000"]
    volumeMounts:
    - name: pod-shared-volume
      mountPath: /shared-dir
    - name: pod-shared-volume-memory
      mountPath: /shared-dir-memory   
  volumes:
  - name: pod-shared-volume
    emptyDir: {}
  - name: pod-shared-volume-memory
    emptyDir:
      medium: Memory
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-volumes-hostpath
spec:
  containers:
  - name: container
    image: sbeliakou/curl
    command: ["sleep", "1000"]
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
    - name: data-storage
      mountPath: /etc/app-data
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  - name: data-storage
    hostPath:
      path: /etc/app-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: localvolume-pv
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master
  capacity: 
    storage: 1Gi
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /tmp
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: localvolume-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 20Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-volumes-localvolume
spec:
  containers:
  - name: container
    image: busybox
    command: ["sleep", "1000"]
    volumeMounts:
    - name: pod-volumes-localvolume-volume
      mountPath: /etc/data

  volumes:
  - name: pod-volumes-localvolume-volume
    persistentVolumeClaim:
      claimName: localvolume-pvc
